/**
 * Final output formatter for ByBet chatbot responses.
 *
 * Runs on every response before returning to the client.
 * Strips markdown, normalizes numbered step markers, and inserts
 * line breaks so instructions render as readable multi-line text.
 *
 * Pure function — no side effects, no AI calls.
 */

/**
 * @param {string} text — raw response text (FAQ or Gemini-generated)
 * @returns {string} plain-text, cleanly formatted response
 */
export function formatBotReply(text) {
  if (typeof text !== "string") return "";

  let out = text.trim();
  if (!out) return "";

  /* ---- Strip markdown ---- */

  out = out.replace(/\*\*([^*]+)\*\*/g, "$1");
  out = out.replace(/\*([^*]+)\*/g, "$1");
  out = out.replace(/^#{1,6}\s+/gm, "");
  out = out.replace(/^\s*[-*]\s+/gm, "");

  /* ---- Normalize step markers and put each step on its own line ---- */

  // (1) text  →  \n1. text
  out = out.replace(/\s*\((\d+)\)\s*/g, "\n$1. ");

  // Inline  N) text  →  \nN. text  (only when preceded by non-whitespace)
  out = out.replace(/(\S)\s+(\d+)\)\s+/g, "$1\n$2. ");

  // Line-start  N) text  →  N. text
  out = out.replace(/^(\d+)\)\s+/gm, "$1. ");

  // Inline "N." steps generated by Gemini after a sentence boundary (N ≥ 2)
  out = out.replace(/([.!?])\s+((?:[2-9]|\d{2,})\.\s)/g, "$1\n$2");

  /* ---- Blank line before the first step in a block ---- */

  out = out.replace(/([^\n])\n(1\.\s)/g, "$1\n\n$2");

  /* ---- Collapse excessive blank lines ---- */

  out = out.replace(/\n{3,}/g, "\n\n");

  /* ---- Trim trailing whitespace per line ---- */

  out = out
    .split("\n")
    .map((line) => line.trimEnd())
    .join("\n")
    .trim();

  return out;
}
